# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'clayground-ios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'shared', :path => '../../shared/'
  pod 'Swinject'


  target 'clayground-iosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'clayground-iosUITests' do
    # Pods for testing
  end

end
