# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'clayground-mac' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'shared', :path => '../shared/'
  pod 'Swinject'


  target 'clayground-macTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'clayground-macUITests' do
    # Pods for testing
  end

end
